GET http://localhost:8080/exam/java/add?questionText=QuestionText&questionAnswer=QuestionAnswer1
###
GET http://localhost:8080/exam/java
###
GET http://localhost:8080/exam/java/remove?questionText=QuestionText&questionAnswer=QuestionAnswer1
###
GET http://localhost:8080/exam/get/6
